version: 2.1

orbs:
  docker: circleci/docker@1.5.0

jobs:
  init:
    docker:
      - image: python:3.8.0
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            # - v1-dependencies-
      - run:
          name: Install dependencies
          command: |
            python3 -m venv .devops
            source .devops/bin/activate
            make install
      - save_cache:
          paths:
            - ./.devops
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Run lint
          command: |
            source .devops/bin/activate
            make lint 


workflows:
  default:
    jobs:
      - init        
      - docker/publish:
          matrix:
            parameters:
              image: [toliv22/capstone]
              path: [capstone]
              docker-context: [capstone]
              deploy: [true]
              # We publish two images with different version tags: 
              # - numbered version
              # - "latest"
              # tag: ['capstone/v1.0.0', 'latest']
              tag: ['capstone/v1.0.0', 'latest']
              update-description: [true]    
          requires: [init]
